# Generated by Django 3.2.7 on 2021-09-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0005_alter_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
