# Generated by Django 3.2.7 on 2021-09-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0009_auto_20210916_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
