# Generated by Django 3.2.7 on 2021-09-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_user',
            new_name='user',
        ),
    ]
